### ISSUE TITLE
Hi Hannover

### ISSUE THREAD

**Issue by wogoos** [ArduinoHannover/NTP#1]
I did a Compile of your SMTP client and got list of errors. Can you assist on how to solve this. My feeling is that these time and day variables are unknown to ESPMailer.cpp and should be declared within NTP. How can I make these variables know to ESPMailer.cpp
Thanks

Compiling 'ESP8266_SMTP_Client' for 'Generic ESP8266 Module'
ESPMailer.cpp: In member function boolean ESPMailer::send()
 
ESPMailer.cpp: 285:25: error: 'weekday' was not declared in this scope
   dayShortStr(weekday(tm))
 
ESPMailer.cpp: 285:26: error: 'dayShortStr' was not declared in this scope
   dayShortStr(weekday(tm))
 
ESPMailer.cpp: 288:9: error: 'day' was not declared in this scope
   day(tm)
 
ESPMailer.cpp: 289:25: error: 'month' was not declared in this scope
   monthShortStr(month(tm))
 
ESPMailer.cpp: 289:26: error: 'monthShortStr' was not declared in this scope
   monthShortStr(month(tm))
 
ESPMailer.cpp: 290:10: error: 'year' was not declared in this scope
   year(tm)
 
ESPMailer.cpp: 291:10: error: 'hour' was not declared in this scope
   hour(tm)
 
ESPMailer.cpp: 292:12: error: 'minute' was not declared in this scope
   minute(tm)
 
ESPMailer.cpp: 293:12: error: 'second' was not declared in this scope
   second(tm)
NTP.cpp: In member function time_t NTP::get(float)
 
NTP.cpp: 60:53: error: 'SECS_PER_HOUR' was not declared in this scope
   return secsSince1900 - seventyYears + timezone * SECS_PER_HOUR
Error compiling libraries
Build failed for project 'ESP8266_SMTP_Client'

**Comment by programmer131** [comment]
replace time.h with TimeLib.h, 

#include <ESP8266WiFi.h>
#include "ESPMailer.h"
#include "TimeLib.h"
#include <NTP.h>

**Comment by wogoos** [comment]
Hi farrukh, 

Thanks for the response I did it and now it works. 

Any experience with TFT displays and esp8266-12e. I’m trying to understand the drivers and the principals to  access these ILI9341 driver chips.

Andy way thanks for the help

Oscar  

 

Van: Farrukh [mailto:notifications@github.com] 
Verzonden: Friday, June 9, 2017 23:57
Aan: ArduinoHannover/NTP
CC: wogoos; Author
Onderwerp: Re: [ArduinoHannover/NTP] Hi Hannover (#1)

 

replace time.h with TimeLib.h,

#include <ESP8266WiFi.h>
#include "ESPMailer.h"
#include "TimeLib.h"
#include <NTP.h>
